apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: envmgr
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAVCCMb2btMdQgs7iOlaQ5JHCTenyEw9WJtEdZS2C9USYmaalP/hTMMbQJP3qiBlhcohSJVa+UQ7sEIvLPupFzr2Tj0EZOgZOKZtj/NQiNIz9GOuOHv9Fuw4Ebr+5kIwTDhJ4hjgSoffqR7vCsBlPnOopu53eT+OylD3GfgBYkgT9GLJLhsTUIdDDDElqD1sEgpvf19Vtl3YQhk3WzKUWGnEmztoQ11oRagYcilqtkR6UXa1tVlkpQ5cb20Ds/qz8vP3CjRXBvhSN1KLa1Jysr0OJpMX8rEUK1JAx7QaelI0SwdAh17g19B5EtdJKEKK6Bo172iBEJjZfKDzoLVQ7rZIC+0lryYSMXeYou2sHmqseysD2Z2HwZBnHlZYonDnEXjp6WUF+Epf3g8CEXoqJgQqsGcDqgzA977riATSAOGMzh3pylWhklkB86AljZ9mNtYvf4UFjp01fy0HoPWoxl5sx2V0tZOOODkBQ2TVQ==
  template:
    metadata:
      creationTimestamp: null
      name: envmgr
      namespace: default

